name: Translate README

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Met à jour vers la dernière version de checkout
      - uses: actions/checkout@v3
      - name: Setup Node.js
        # Utilise une version plus récente de setup-node
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
      # Traduction en anglais
      - name: Adding README - English
        uses: dephraiim/translate-readme@main
        with:
          LANG: en
